# 
# doerker compose使用配置
# 
# include:
#       - /path/to/compose.yaml
# service:
#       <service-name>：
#           container_name: <container_name>
#           env_file:
#               - <env_file>
#           environment:
#               KEY: VAL
#           expose:
#               - <portnum>/[<proto>]
#           configs:
#               - <config-name>
#           networks:
#               - <network-name>
#           volumes:
#               - VOLUME:CONTAINER_PATH:ACCESS_MODE
#           ports:
#               - [HOST:]CONTAINER[/PROTOCOL]
#           restart: no | always | on-failure[:max-retries] | unless-stopped
#           depends_on:
#               - <service-name>
# configs:
#       <config-name>:
#           KEY: VAL
# networks:
#       <network-name>:
#           driver: bridge | host | overlay | none
# volumes:
#       <volume-name>